// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/quiz.proto

package quiz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Difficulty int32

const (
	Difficulty_DIFFICULTY_UNSPECIFIED Difficulty = 0
	Difficulty_EASY                   Difficulty = 1
	Difficulty_MEDIUM                 Difficulty = 2
	Difficulty_HARD                   Difficulty = 3
)

// Enum value maps for Difficulty.
var (
	Difficulty_name = map[int32]string{
		0: "DIFFICULTY_UNSPECIFIED",
		1: "EASY",
		2: "MEDIUM",
		3: "HARD",
	}
	Difficulty_value = map[string]int32{
		"DIFFICULTY_UNSPECIFIED": 0,
		"EASY":                   1,
		"MEDIUM":                 2,
		"HARD":                   3,
	}
)

func (x Difficulty) Enum() *Difficulty {
	p := new(Difficulty)
	*p = x
	return p
}

func (x Difficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Difficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_quiz_proto_enumTypes[0].Descriptor()
}

func (Difficulty) Type() protoreflect.EnumType {
	return &file_proto_quiz_proto_enumTypes[0]
}

func (x Difficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Difficulty.Descriptor instead.
func (Difficulty) EnumDescriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0}
}

type MatchState int32

const (
	MatchState_MATCH_STATE_UNSPECIFIED MatchState = 0
	MatchState_WAITING                 MatchState = 1
	MatchState_IN_PROGRESS             MatchState = 2
	MatchState_FINISHED                MatchState = 3
)

// Enum value maps for MatchState.
var (
	MatchState_name = map[int32]string{
		0: "MATCH_STATE_UNSPECIFIED",
		1: "WAITING",
		2: "IN_PROGRESS",
		3: "FINISHED",
	}
	MatchState_value = map[string]int32{
		"MATCH_STATE_UNSPECIFIED": 0,
		"WAITING":                 1,
		"IN_PROGRESS":             2,
		"FINISHED":                3,
	}
)

func (x MatchState) Enum() *MatchState {
	p := new(MatchState)
	*p = x
	return p
}

func (x MatchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_quiz_proto_enumTypes[1].Descriptor()
}

func (MatchState) Type() protoreflect.EnumType {
	return &file_proto_quiz_proto_enumTypes[1]
}

func (x MatchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchState.Descriptor instead.
func (MatchState) EnumDescriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1}
}

type PlayerStatus int32

const (
	PlayerStatus_PLAYER_STATUS_UNSPECIFIED PlayerStatus = 0
	PlayerStatus_CONNECTED                 PlayerStatus = 1
	PlayerStatus_DISCONNECTED              PlayerStatus = 2
	PlayerStatus_RECONNECTING              PlayerStatus = 3
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "PLAYER_STATUS_UNSPECIFIED",
		1: "CONNECTED",
		2: "DISCONNECTED",
		3: "RECONNECTING",
	}
	PlayerStatus_value = map[string]int32{
		"PLAYER_STATUS_UNSPECIFIED": 0,
		"CONNECTED":                 1,
		"DISCONNECTED":              2,
		"RECONNECTING":              3,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_quiz_proto_enumTypes[2].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_proto_quiz_proto_enumTypes[2]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{2}
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // JWT
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"` // error or info message
	Rating        int32                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthResponse) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Status        PlayerStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=quiz.PlayerStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Player) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_PLAYER_STATUS_UNSPECIFIED
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"` // always 4 options
	Difficulty    Difficulty             `protobuf:"varint,4,opt,name=difficulty,proto3,enum=quiz.Difficulty" json:"difficulty,omitempty"`
	Topic         string                 `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	TimeLimitMs   int32                  `protobuf:"varint,6,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"` // per-question timer based on avgResponseTimeMs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *Question) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetDifficulty() Difficulty {
	if x != nil {
		return x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *Question) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Question) GetTimeLimitMs() int32 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

type PlayerScore struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Score          int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Rank           int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	AnswersCorrect int32                  `protobuf:"varint,5,opt,name=answers_correct,json=answersCorrect,proto3" json:"answers_correct,omitempty"`
	AvgResponseMs  int32                  `protobuf:"varint,6,opt,name=avg_response_ms,json=avgResponseMs,proto3" json:"avg_response_ms,omitempty"`
	IsConnected    bool                   `protobuf:"varint,7,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerScore) Reset() {
	*x = PlayerScore{}
	mi := &file_proto_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerScore) ProtoMessage() {}

func (x *PlayerScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerScore.ProtoReflect.Descriptor instead.
func (*PlayerScore) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerScore) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerScore) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerScore) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *PlayerScore) GetAnswersCorrect() int32 {
	if x != nil {
		return x.AnswersCorrect
	}
	return 0
}

func (x *PlayerScore) GetAvgResponseMs() int32 {
	if x != nil {
		return x.AvgResponseMs
	}
	return 0
}

func (x *PlayerScore) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

// JoinMatchmaking
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JoinRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                  // e.g. "Added to pool, waiting for players..."
	QueuePosition string                 `protobuf:"bytes,3,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"` // informational ETA hint for the UI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_proto_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *JoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinResponse) GetQueuePosition() string {
	if x != nil {
		return x.QueuePosition
	}
	return ""
}

// LeaveMatchmaking
type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_proto_quiz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_proto_quiz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SubscribeToMatch — streamed events back to Flutter
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_quiz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*MatchEvent_MatchFound
	//	*MatchEvent_MatchCancelled
	//	*MatchEvent_WaitingUpdate
	Event         isMatchEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEvent) Reset() {
	*x = MatchEvent{}
	mi := &file_proto_quiz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEvent) ProtoMessage() {}

func (x *MatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEvent.ProtoReflect.Descriptor instead.
func (*MatchEvent) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{10}
}

func (x *MatchEvent) GetEvent() isMatchEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MatchEvent) GetMatchFound() *MatchFound {
	if x != nil {
		if x, ok := x.Event.(*MatchEvent_MatchFound); ok {
			return x.MatchFound
		}
	}
	return nil
}

func (x *MatchEvent) GetMatchCancelled() *MatchCancelled {
	if x != nil {
		if x, ok := x.Event.(*MatchEvent_MatchCancelled); ok {
			return x.MatchCancelled
		}
	}
	return nil
}

func (x *MatchEvent) GetWaitingUpdate() *WaitingUpdate {
	if x != nil {
		if x, ok := x.Event.(*MatchEvent_WaitingUpdate); ok {
			return x.WaitingUpdate
		}
	}
	return nil
}

type isMatchEvent_Event interface {
	isMatchEvent_Event()
}

type MatchEvent_MatchFound struct {
	MatchFound *MatchFound `protobuf:"bytes,1,opt,name=match_found,json=matchFound,proto3,oneof"`
}

type MatchEvent_MatchCancelled struct {
	MatchCancelled *MatchCancelled `protobuf:"bytes,2,opt,name=match_cancelled,json=matchCancelled,proto3,oneof"`
}

type MatchEvent_WaitingUpdate struct {
	WaitingUpdate *WaitingUpdate `protobuf:"bytes,3,opt,name=waiting_update,json=waitingUpdate,proto3,oneof"`
}

func (*MatchEvent_MatchFound) isMatchEvent_Event() {}

func (*MatchEvent_MatchCancelled) isMatchEvent_Event() {}

func (*MatchEvent_WaitingUpdate) isMatchEvent_Event() {}

type MatchFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	TotalRounds   int32                  `protobuf:"varint,3,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFound) Reset() {
	*x = MatchFound{}
	mi := &file_proto_quiz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFound) ProtoMessage() {}

func (x *MatchFound) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFound.ProtoReflect.Descriptor instead.
func (*MatchFound) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{11}
}

func (x *MatchFound) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchFound) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchFound) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

type MatchCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // "timeout" | "not_enough_players"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCancelled) Reset() {
	*x = MatchCancelled{}
	mi := &file_proto_quiz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelled) ProtoMessage() {}

func (x *MatchCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelled.ProtoReflect.Descriptor instead.
func (*MatchCancelled) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{12}
}

func (x *MatchCancelled) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type WaitingUpdate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PlayersInPool        int32                  `protobuf:"varint,1,opt,name=players_in_pool,json=playersInPool,proto3" json:"players_in_pool,omitempty"`
	EstimatedWaitSeconds int32                  `protobuf:"varint,2,opt,name=estimated_wait_seconds,json=estimatedWaitSeconds,proto3" json:"estimated_wait_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WaitingUpdate) Reset() {
	*x = WaitingUpdate{}
	mi := &file_proto_quiz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitingUpdate) ProtoMessage() {}

func (x *WaitingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitingUpdate.ProtoReflect.Descriptor instead.
func (*WaitingUpdate) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{13}
}

func (x *WaitingUpdate) GetPlayersInPool() int32 {
	if x != nil {
		return x.PlayersInPool
	}
	return 0
}

func (x *WaitingUpdate) GetEstimatedWaitSeconds() int32 {
	if x != nil {
		return x.EstimatedWaitSeconds
	}
	return 0
}

// GetRoomQuestions
type RoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomRequest) Reset() {
	*x = RoomRequest{}
	mi := &file_proto_quiz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRequest) ProtoMessage() {}

func (x *RoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRequest.ProtoReflect.Descriptor instead.
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{14}
}

func (x *RoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type QuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	TotalRounds   int32                  `protobuf:"varint,3,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionsResponse) Reset() {
	*x = QuestionsResponse{}
	mi := &file_proto_quiz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionsResponse) ProtoMessage() {}

func (x *QuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionsResponse.ProtoReflect.Descriptor instead.
func (*QuestionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{15}
}

func (x *QuestionsResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *QuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *QuestionsResponse) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

// SubmitAnswer
type AnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoundNumber   int32                  `protobuf:"varint,3,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	QuestionId    string                 `protobuf:"bytes,4,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerIndex   int32                  `protobuf:"varint,5,opt,name=answer_index,json=answerIndex,proto3" json:"answer_index,omitempty"`         // 0–3 matching options array
	SubmittedAtMs int64                  `protobuf:"varint,6,opt,name=submitted_at_ms,json=submittedAtMs,proto3" json:"submitted_at_ms,omitempty"` // client epoch ms — used for speed scoring
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	mi := &file_proto_quiz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{16}
}

func (x *AnswerRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AnswerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnswerRequest) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *AnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *AnswerRequest) GetAnswerIndex() int32 {
	if x != nil {
		return x.AnswerIndex
	}
	return 0
}

func (x *AnswerRequest) GetSubmittedAtMs() int64 {
	if x != nil {
		return x.SubmittedAtMs
	}
	return 0
}

type AnswerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // "Answer recorded" | "Too late" | "Already submitted"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerAck) Reset() {
	*x = AnswerAck{}
	mi := &file_proto_quiz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerAck) ProtoMessage() {}

func (x *AnswerAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerAck.ProtoReflect.Descriptor instead.
func (*AnswerAck) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{17}
}

func (x *AnswerAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *AnswerAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StreamGameEvents
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_quiz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{18}
}

func (x *StreamRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StreamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GameEvent — the core real-time envelope sent to every Flutter client
type GameEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*GameEvent_Question
	//	*GameEvent_Leaderboard
	//	*GameEvent_RoundResult
	//	*GameEvent_MatchEnd
	//	*GameEvent_PlayerJoined
	//	*GameEvent_TimerSync
	Event         isGameEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_proto_quiz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{19}
}

func (x *GameEvent) GetEvent() isGameEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GameEvent) GetQuestion() *QuestionBroadcast {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_Question); ok {
			return x.Question
		}
	}
	return nil
}

func (x *GameEvent) GetLeaderboard() *LeaderboardUpdate {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_Leaderboard); ok {
			return x.Leaderboard
		}
	}
	return nil
}

func (x *GameEvent) GetRoundResult() *RoundResult {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_RoundResult); ok {
			return x.RoundResult
		}
	}
	return nil
}

func (x *GameEvent) GetMatchEnd() *MatchEnd {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_MatchEnd); ok {
			return x.MatchEnd
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerJoined() *PlayerJoined {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_PlayerJoined); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

func (x *GameEvent) GetTimerSync() *TimerSync {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_TimerSync); ok {
			return x.TimerSync
		}
	}
	return nil
}

type isGameEvent_Event interface {
	isGameEvent_Event()
}

type GameEvent_Question struct {
	Question *QuestionBroadcast `protobuf:"bytes,1,opt,name=question,proto3,oneof"`
}

type GameEvent_Leaderboard struct {
	Leaderboard *LeaderboardUpdate `protobuf:"bytes,2,opt,name=leaderboard,proto3,oneof"`
}

type GameEvent_RoundResult struct {
	RoundResult *RoundResult `protobuf:"bytes,3,opt,name=round_result,json=roundResult,proto3,oneof"`
}

type GameEvent_MatchEnd struct {
	MatchEnd *MatchEnd `protobuf:"bytes,4,opt,name=match_end,json=matchEnd,proto3,oneof"`
}

type GameEvent_PlayerJoined struct {
	PlayerJoined *PlayerJoined `protobuf:"bytes,5,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

type GameEvent_TimerSync struct {
	TimerSync *TimerSync `protobuf:"bytes,6,opt,name=timer_sync,json=timerSync,proto3,oneof"`
}

func (*GameEvent_Question) isGameEvent_Event() {}

func (*GameEvent_Leaderboard) isGameEvent_Event() {}

func (*GameEvent_RoundResult) isGameEvent_Event() {}

func (*GameEvent_MatchEnd) isGameEvent_Event() {}

func (*GameEvent_PlayerJoined) isGameEvent_Event() {}

func (*GameEvent_TimerSync) isGameEvent_Event() {}

// Sent at the start of each round — shows the question + starts countdown
type QuestionBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber   int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Question      *Question              `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	DeadlineMs    int64                  `protobuf:"varint,3,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"` // absolute epoch ms when round closes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionBroadcast) Reset() {
	*x = QuestionBroadcast{}
	mi := &file_proto_quiz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionBroadcast) ProtoMessage() {}

func (x *QuestionBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionBroadcast.ProtoReflect.Descriptor instead.
func (*QuestionBroadcast) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{20}
}

func (x *QuestionBroadcast) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *QuestionBroadcast) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *QuestionBroadcast) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

// Sent after every score update — refreshes the leaderboard overlay
type LeaderboardUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoundNumber   int32                  `protobuf:"varint,2,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Scores        []*PlayerScore         `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardUpdate) Reset() {
	*x = LeaderboardUpdate{}
	mi := &file_proto_quiz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardUpdate) ProtoMessage() {}

func (x *LeaderboardUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardUpdate.ProtoReflect.Descriptor instead.
func (*LeaderboardUpdate) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{21}
}

func (x *LeaderboardUpdate) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LeaderboardUpdate) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *LeaderboardUpdate) GetScores() []*PlayerScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

// Sent after all answers are in (or timer expires) for a round
type RoundResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber   int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	CorrectIndex  int32                  `protobuf:"varint,3,opt,name=correct_index,json=correctIndex,proto3" json:"correct_index,omitempty"` // revealed to clients after round ends
	Scores        []*PlayerScore         `protobuf:"bytes,4,rep,name=scores,proto3" json:"scores,omitempty"`
	FastestUserId string                 `protobuf:"bytes,5,opt,name=fastest_user_id,json=fastestUserId,proto3" json:"fastest_user_id,omitempty"` // who answered fastest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundResult) Reset() {
	*x = RoundResult{}
	mi := &file_proto_quiz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundResult) ProtoMessage() {}

func (x *RoundResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundResult.ProtoReflect.Descriptor instead.
func (*RoundResult) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{22}
}

func (x *RoundResult) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *RoundResult) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *RoundResult) GetCorrectIndex() int32 {
	if x != nil {
		return x.CorrectIndex
	}
	return 0
}

func (x *RoundResult) GetScores() []*PlayerScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *RoundResult) GetFastestUserId() string {
	if x != nil {
		return x.FastestUserId
	}
	return ""
}

// Sent once at the very end of the match
type MatchEnd struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	WinnerUserId    string                 `protobuf:"bytes,2,opt,name=winner_user_id,json=winnerUserId,proto3" json:"winner_user_id,omitempty"`
	WinnerUsername  string                 `protobuf:"bytes,3,opt,name=winner_username,json=winnerUsername,proto3" json:"winner_username,omitempty"`
	FinalScores     []*PlayerScore         `protobuf:"bytes,4,rep,name=final_scores,json=finalScores,proto3" json:"final_scores,omitempty"`
	TotalRounds     int32                  `protobuf:"varint,5,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchEnd) Reset() {
	*x = MatchEnd{}
	mi := &file_proto_quiz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEnd) ProtoMessage() {}

func (x *MatchEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEnd.ProtoReflect.Descriptor instead.
func (*MatchEnd) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{23}
}

func (x *MatchEnd) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchEnd) GetWinnerUserId() string {
	if x != nil {
		return x.WinnerUserId
	}
	return ""
}

func (x *MatchEnd) GetWinnerUsername() string {
	if x != nil {
		return x.WinnerUsername
	}
	return ""
}

func (x *MatchEnd) GetFinalScores() []*PlayerScore {
	if x != nil {
		return x.FinalScores
	}
	return nil
}

func (x *MatchEnd) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *MatchEnd) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// Sent when a new player connects or reconnects mid-match
type PlayerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	RoundNumber   int32                  `protobuf:"varint,2,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"` // current round so late joiner can catch up
	State         MatchState             `protobuf:"varint,3,opt,name=state,proto3,enum=quiz.MatchState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoined) Reset() {
	*x = PlayerJoined{}
	mi := &file_proto_quiz_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoined) ProtoMessage() {}

func (x *PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoined.ProtoReflect.Descriptor instead.
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{24}
}

func (x *PlayerJoined) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerJoined) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *PlayerJoined) GetState() MatchState {
	if x != nil {
		return x.State
	}
	return MatchState_MATCH_STATE_UNSPECIFIED
}

// Sent periodically to keep client clocks in sync with server
type TimerSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber   int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	ServerTimeMs  int64                  `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"` // server epoch ms — client computes drift offset
	DeadlineMs    int64                  `protobuf:"varint,3,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`         // when current round closes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerSync) Reset() {
	*x = TimerSync{}
	mi := &file_proto_quiz_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerSync) ProtoMessage() {}

func (x *TimerSync) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerSync.ProtoReflect.Descriptor instead.
func (*TimerSync) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{25}
}

func (x *TimerSync) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *TimerSync) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *TimerSync) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

// CalculateScore
type ScoreRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RoomId           string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoundNumber      int32                  `protobuf:"varint,3,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	QuestionId       string                 `protobuf:"bytes,4,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerIndex      int32                  `protobuf:"varint,5,opt,name=answer_index,json=answerIndex,proto3" json:"answer_index,omitempty"`
	SubmittedAtMs    int64                  `protobuf:"varint,6,opt,name=submitted_at_ms,json=submittedAtMs,proto3" json:"submitted_at_ms,omitempty"`
	RoundStartedAtMs int64                  `protobuf:"varint,7,opt,name=round_started_at_ms,json=roundStartedAtMs,proto3" json:"round_started_at_ms,omitempty"` // used to compute response time for speed bonus
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_proto_quiz_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{26}
}

func (x *ScoreRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScoreRequest) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *ScoreRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *ScoreRequest) GetAnswerIndex() int32 {
	if x != nil {
		return x.AnswerIndex
	}
	return 0
}

func (x *ScoreRequest) GetSubmittedAtMs() int64 {
	if x != nil {
		return x.SubmittedAtMs
	}
	return 0
}

func (x *ScoreRequest) GetRoundStartedAtMs() int64 {
	if x != nil {
		return x.RoundStartedAtMs
	}
	return 0
}

type ScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCorrect     bool                   `protobuf:"varint,1,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	PointsAwarded int32                  `protobuf:"varint,2,opt,name=points_awarded,json=pointsAwarded,proto3" json:"points_awarded,omitempty"` // base + speed bonus
	TotalScore    int32                  `protobuf:"varint,3,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`          // cumulative score for this player in this room
	SpeedBonus    int32                  `protobuf:"varint,4,opt,name=speed_bonus,json=speedBonus,proto3" json:"speed_bonus,omitempty"`          // extra points for fast answer
	NewRank       int32                  `protobuf:"varint,5,opt,name=new_rank,json=newRank,proto3" json:"new_rank,omitempty"`                   // rank after this score update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_proto_quiz_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{27}
}

func (x *ScoreResponse) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *ScoreResponse) GetPointsAwarded() int32 {
	if x != nil {
		return x.PointsAwarded
	}
	return 0
}

func (x *ScoreResponse) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *ScoreResponse) GetSpeedBonus() int32 {
	if x != nil {
		return x.SpeedBonus
	}
	return 0
}

func (x *ScoreResponse) GetNewRank() int32 {
	if x != nil {
		return x.NewRank
	}
	return 0
}

// GetLeaderboard
type LeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardRequest) Reset() {
	*x = LeaderboardRequest{}
	mi := &file_proto_quiz_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardRequest) ProtoMessage() {}

func (x *LeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardRequest.ProtoReflect.Descriptor instead.
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{28}
}

func (x *LeaderboardRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoundNumber   int32                  `protobuf:"varint,2,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	Scores        []*PlayerScore         `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardResponse) Reset() {
	*x = LeaderboardResponse{}
	mi := &file_proto_quiz_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResponse) ProtoMessage() {}

func (x *LeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResponse.ProtoReflect.Descriptor instead.
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{29}
}

func (x *LeaderboardResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LeaderboardResponse) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *LeaderboardResponse) GetScores() []*PlayerScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_proto_quiz_proto protoreflect.FileDescriptor

const file_proto_quiz_proto_rawDesc = "" +
	"\n" +
	"\x10proto/quiz.proto\x12\x04quiz\"E\n" +
	"\vAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa5\x01\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\"\x81\x01\n" +
	"\x06Player\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.quiz.PlayerStatusR\x06status\"\xc5\x01\n" +
	"\bQuestion\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x120\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x0e2\x10.quiz.DifficultyR\n" +
	"difficulty\x12\x14\n" +
	"\x05topic\x18\x05 \x01(\tR\x05topic\x12\"\n" +
	"\rtime_limit_ms\x18\x06 \x01(\x05R\vtimeLimitMs\"\xe0\x01\n" +
	"\vPlayerScore\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12'\n" +
	"\x0fanswers_correct\x18\x05 \x01(\x05R\x0eanswersCorrect\x12&\n" +
	"\x0favg_response_ms\x18\x06 \x01(\x05R\ravgResponseMs\x12!\n" +
	"\fis_connected\x18\a \x01(\bR\visConnected\"Z\n" +
	"\vJoinRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\"i\n" +
	"\fJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0equeue_position\x18\x03 \x01(\tR\rqueuePosition\"'\n" +
	"\fLeaveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\rLeaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xc9\x01\n" +
	"\n" +
	"MatchEvent\x123\n" +
	"\vmatch_found\x18\x01 \x01(\v2\x10.quiz.MatchFoundH\x00R\n" +
	"matchFound\x12?\n" +
	"\x0fmatch_cancelled\x18\x02 \x01(\v2\x14.quiz.MatchCancelledH\x00R\x0ematchCancelled\x12<\n" +
	"\x0ewaiting_update\x18\x03 \x01(\v2\x13.quiz.WaitingUpdateH\x00R\rwaitingUpdateB\a\n" +
	"\x05event\"p\n" +
	"\n" +
	"MatchFound\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12&\n" +
	"\aplayers\x18\x02 \x03(\v2\f.quiz.PlayerR\aplayers\x12!\n" +
	"\ftotal_rounds\x18\x03 \x01(\x05R\vtotalRounds\"(\n" +
	"\x0eMatchCancelled\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"m\n" +
	"\rWaitingUpdate\x12&\n" +
	"\x0fplayers_in_pool\x18\x01 \x01(\x05R\rplayersInPool\x124\n" +
	"\x16estimated_wait_seconds\x18\x02 \x01(\x05R\x14estimatedWaitSeconds\"?\n" +
	"\vRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"}\n" +
	"\x11QuestionsResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12,\n" +
	"\tquestions\x18\x02 \x03(\v2\x0e.quiz.QuestionR\tquestions\x12!\n" +
	"\ftotal_rounds\x18\x03 \x01(\x05R\vtotalRounds\"\xd0\x01\n" +
	"\rAnswerRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fround_number\x18\x03 \x01(\x05R\vroundNumber\x12\x1f\n" +
	"\vquestion_id\x18\x04 \x01(\tR\n" +
	"questionId\x12!\n" +
	"\fanswer_index\x18\x05 \x01(\x05R\vanswerIndex\x12&\n" +
	"\x0fsubmitted_at_ms\x18\x06 \x01(\x03R\rsubmittedAtMs\"A\n" +
	"\tAnswerAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\rStreamRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xdc\x02\n" +
	"\tGameEvent\x125\n" +
	"\bquestion\x18\x01 \x01(\v2\x17.quiz.QuestionBroadcastH\x00R\bquestion\x12;\n" +
	"\vleaderboard\x18\x02 \x01(\v2\x17.quiz.LeaderboardUpdateH\x00R\vleaderboard\x126\n" +
	"\fround_result\x18\x03 \x01(\v2\x11.quiz.RoundResultH\x00R\vroundResult\x12-\n" +
	"\tmatch_end\x18\x04 \x01(\v2\x0e.quiz.MatchEndH\x00R\bmatchEnd\x129\n" +
	"\rplayer_joined\x18\x05 \x01(\v2\x12.quiz.PlayerJoinedH\x00R\fplayerJoined\x120\n" +
	"\n" +
	"timer_sync\x18\x06 \x01(\v2\x0f.quiz.TimerSyncH\x00R\ttimerSyncB\a\n" +
	"\x05event\"\x83\x01\n" +
	"\x11QuestionBroadcast\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\x12*\n" +
	"\bquestion\x18\x02 \x01(\v2\x0e.quiz.QuestionR\bquestion\x12\x1f\n" +
	"\vdeadline_ms\x18\x03 \x01(\x03R\n" +
	"deadlineMs\"z\n" +
	"\x11LeaderboardUpdate\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\fround_number\x18\x02 \x01(\x05R\vroundNumber\x12)\n" +
	"\x06scores\x18\x03 \x03(\v2\x11.quiz.PlayerScoreR\x06scores\"\xc9\x01\n" +
	"\vRoundResult\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12#\n" +
	"\rcorrect_index\x18\x03 \x01(\x05R\fcorrectIndex\x12)\n" +
	"\x06scores\x18\x04 \x03(\v2\x11.quiz.PlayerScoreR\x06scores\x12&\n" +
	"\x0ffastest_user_id\x18\x05 \x01(\tR\rfastestUserId\"\xf6\x01\n" +
	"\bMatchEnd\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12$\n" +
	"\x0ewinner_user_id\x18\x02 \x01(\tR\fwinnerUserId\x12'\n" +
	"\x0fwinner_username\x18\x03 \x01(\tR\x0ewinnerUsername\x124\n" +
	"\ffinal_scores\x18\x04 \x03(\v2\x11.quiz.PlayerScoreR\vfinalScores\x12!\n" +
	"\ftotal_rounds\x18\x05 \x01(\x05R\vtotalRounds\x12)\n" +
	"\x10duration_seconds\x18\x06 \x01(\x05R\x0fdurationSeconds\"\x7f\n" +
	"\fPlayerJoined\x12$\n" +
	"\x06player\x18\x01 \x01(\v2\f.quiz.PlayerR\x06player\x12!\n" +
	"\fround_number\x18\x02 \x01(\x05R\vroundNumber\x12&\n" +
	"\x05state\x18\x03 \x01(\x0e2\x10.quiz.MatchStateR\x05state\"u\n" +
	"\tTimerSync\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\x12$\n" +
	"\x0eserver_time_ms\x18\x02 \x01(\x03R\fserverTimeMs\x12\x1f\n" +
	"\vdeadline_ms\x18\x03 \x01(\x03R\n" +
	"deadlineMs\"\xfe\x01\n" +
	"\fScoreRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fround_number\x18\x03 \x01(\x05R\vroundNumber\x12\x1f\n" +
	"\vquestion_id\x18\x04 \x01(\tR\n" +
	"questionId\x12!\n" +
	"\fanswer_index\x18\x05 \x01(\x05R\vanswerIndex\x12&\n" +
	"\x0fsubmitted_at_ms\x18\x06 \x01(\x03R\rsubmittedAtMs\x12-\n" +
	"\x13round_started_at_ms\x18\a \x01(\x03R\x10roundStartedAtMs\"\xb2\x01\n" +
	"\rScoreResponse\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x01 \x01(\bR\tisCorrect\x12%\n" +
	"\x0epoints_awarded\x18\x02 \x01(\x05R\rpointsAwarded\x12\x1f\n" +
	"\vtotal_score\x18\x03 \x01(\x05R\n" +
	"totalScore\x12\x1f\n" +
	"\vspeed_bonus\x18\x04 \x01(\x05R\n" +
	"speedBonus\x12\x19\n" +
	"\bnew_rank\x18\x05 \x01(\x05R\anewRank\"-\n" +
	"\x12LeaderboardRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"|\n" +
	"\x13LeaderboardResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\fround_number\x18\x02 \x01(\x05R\vroundNumber\x12)\n" +
	"\x06scores\x18\x03 \x03(\v2\x11.quiz.PlayerScoreR\x06scores*H\n" +
	"\n" +
	"Difficulty\x12\x1a\n" +
	"\x16DIFFICULTY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04EASY\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HARD\x10\x03*U\n" +
	"\n" +
	"MatchState\x12\x1b\n" +
	"\x17MATCH_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aWAITING\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\f\n" +
	"\bFINISHED\x10\x03*`\n" +
	"\fPlayerStatus\x12\x1d\n" +
	"\x19PLAYER_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCONNECTED\x10\x01\x12\x10\n" +
	"\fDISCONNECTED\x10\x02\x12\x10\n" +
	"\fRECONNECTING\x10\x032p\n" +
	"\vAuthService\x121\n" +
	"\bRegister\x12\x11.quiz.AuthRequest\x1a\x12.quiz.AuthResponse\x12.\n" +
	"\x05Login\x12\x11.quiz.AuthRequest\x1a\x12.quiz.AuthResponse2\xcb\x01\n" +
	"\x12MatchmakingService\x128\n" +
	"\x0fJoinMatchmaking\x12\x11.quiz.JoinRequest\x1a\x12.quiz.JoinResponse\x12;\n" +
	"\x10LeaveMatchmaking\x12\x12.quiz.LeaveRequest\x1a\x13.quiz.LeaveResponse\x12>\n" +
	"\x10SubscribeToMatch\x12\x16.quiz.SubscribeRequest\x1a\x10.quiz.MatchEvent0\x012\xbf\x01\n" +
	"\vQuizService\x12>\n" +
	"\x10GetRoomQuestions\x12\x11.quiz.RoomRequest\x1a\x17.quiz.QuestionsResponse\x124\n" +
	"\fSubmitAnswer\x12\x13.quiz.AnswerRequest\x1a\x0f.quiz.AnswerAck\x12:\n" +
	"\x10StreamGameEvents\x12\x13.quiz.StreamRequest\x1a\x0f.quiz.GameEvent0\x012\x92\x01\n" +
	"\x0eScoringService\x129\n" +
	"\x0eCalculateScore\x12\x12.quiz.ScoreRequest\x1a\x13.quiz.ScoreResponse\x12E\n" +
	"\x0eGetLeaderboard\x12\x18.quiz.LeaderboardRequest\x1a\x19.quiz.LeaderboardResponseB+Z)github.com/yourorg/quiz-battle/proto/quizb\x06proto3"

var (
	file_proto_quiz_proto_rawDescOnce sync.Once
	file_proto_quiz_proto_rawDescData []byte
)

func file_proto_quiz_proto_rawDescGZIP() []byte {
	file_proto_quiz_proto_rawDescOnce.Do(func() {
		file_proto_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quiz_proto_rawDesc), len(file_proto_quiz_proto_rawDesc)))
	})
	return file_proto_quiz_proto_rawDescData
}

var file_proto_quiz_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_quiz_proto_goTypes = []any{
	(Difficulty)(0),             // 0: quiz.Difficulty
	(MatchState)(0),             // 1: quiz.MatchState
	(PlayerStatus)(0),           // 2: quiz.PlayerStatus
	(*AuthRequest)(nil),         // 3: quiz.AuthRequest
	(*AuthResponse)(nil),        // 4: quiz.AuthResponse
	(*Player)(nil),              // 5: quiz.Player
	(*Question)(nil),            // 6: quiz.Question
	(*PlayerScore)(nil),         // 7: quiz.PlayerScore
	(*JoinRequest)(nil),         // 8: quiz.JoinRequest
	(*JoinResponse)(nil),        // 9: quiz.JoinResponse
	(*LeaveRequest)(nil),        // 10: quiz.LeaveRequest
	(*LeaveResponse)(nil),       // 11: quiz.LeaveResponse
	(*SubscribeRequest)(nil),    // 12: quiz.SubscribeRequest
	(*MatchEvent)(nil),          // 13: quiz.MatchEvent
	(*MatchFound)(nil),          // 14: quiz.MatchFound
	(*MatchCancelled)(nil),      // 15: quiz.MatchCancelled
	(*WaitingUpdate)(nil),       // 16: quiz.WaitingUpdate
	(*RoomRequest)(nil),         // 17: quiz.RoomRequest
	(*QuestionsResponse)(nil),   // 18: quiz.QuestionsResponse
	(*AnswerRequest)(nil),       // 19: quiz.AnswerRequest
	(*AnswerAck)(nil),           // 20: quiz.AnswerAck
	(*StreamRequest)(nil),       // 21: quiz.StreamRequest
	(*GameEvent)(nil),           // 22: quiz.GameEvent
	(*QuestionBroadcast)(nil),   // 23: quiz.QuestionBroadcast
	(*LeaderboardUpdate)(nil),   // 24: quiz.LeaderboardUpdate
	(*RoundResult)(nil),         // 25: quiz.RoundResult
	(*MatchEnd)(nil),            // 26: quiz.MatchEnd
	(*PlayerJoined)(nil),        // 27: quiz.PlayerJoined
	(*TimerSync)(nil),           // 28: quiz.TimerSync
	(*ScoreRequest)(nil),        // 29: quiz.ScoreRequest
	(*ScoreResponse)(nil),       // 30: quiz.ScoreResponse
	(*LeaderboardRequest)(nil),  // 31: quiz.LeaderboardRequest
	(*LeaderboardResponse)(nil), // 32: quiz.LeaderboardResponse
}
var file_proto_quiz_proto_depIdxs = []int32{
	2,  // 0: quiz.Player.status:type_name -> quiz.PlayerStatus
	0,  // 1: quiz.Question.difficulty:type_name -> quiz.Difficulty
	14, // 2: quiz.MatchEvent.match_found:type_name -> quiz.MatchFound
	15, // 3: quiz.MatchEvent.match_cancelled:type_name -> quiz.MatchCancelled
	16, // 4: quiz.MatchEvent.waiting_update:type_name -> quiz.WaitingUpdate
	5,  // 5: quiz.MatchFound.players:type_name -> quiz.Player
	6,  // 6: quiz.QuestionsResponse.questions:type_name -> quiz.Question
	23, // 7: quiz.GameEvent.question:type_name -> quiz.QuestionBroadcast
	24, // 8: quiz.GameEvent.leaderboard:type_name -> quiz.LeaderboardUpdate
	25, // 9: quiz.GameEvent.round_result:type_name -> quiz.RoundResult
	26, // 10: quiz.GameEvent.match_end:type_name -> quiz.MatchEnd
	27, // 11: quiz.GameEvent.player_joined:type_name -> quiz.PlayerJoined
	28, // 12: quiz.GameEvent.timer_sync:type_name -> quiz.TimerSync
	6,  // 13: quiz.QuestionBroadcast.question:type_name -> quiz.Question
	7,  // 14: quiz.LeaderboardUpdate.scores:type_name -> quiz.PlayerScore
	7,  // 15: quiz.RoundResult.scores:type_name -> quiz.PlayerScore
	7,  // 16: quiz.MatchEnd.final_scores:type_name -> quiz.PlayerScore
	5,  // 17: quiz.PlayerJoined.player:type_name -> quiz.Player
	1,  // 18: quiz.PlayerJoined.state:type_name -> quiz.MatchState
	7,  // 19: quiz.LeaderboardResponse.scores:type_name -> quiz.PlayerScore
	3,  // 20: quiz.AuthService.Register:input_type -> quiz.AuthRequest
	3,  // 21: quiz.AuthService.Login:input_type -> quiz.AuthRequest
	8,  // 22: quiz.MatchmakingService.JoinMatchmaking:input_type -> quiz.JoinRequest
	10, // 23: quiz.MatchmakingService.LeaveMatchmaking:input_type -> quiz.LeaveRequest
	12, // 24: quiz.MatchmakingService.SubscribeToMatch:input_type -> quiz.SubscribeRequest
	17, // 25: quiz.QuizService.GetRoomQuestions:input_type -> quiz.RoomRequest
	19, // 26: quiz.QuizService.SubmitAnswer:input_type -> quiz.AnswerRequest
	21, // 27: quiz.QuizService.StreamGameEvents:input_type -> quiz.StreamRequest
	29, // 28: quiz.ScoringService.CalculateScore:input_type -> quiz.ScoreRequest
	31, // 29: quiz.ScoringService.GetLeaderboard:input_type -> quiz.LeaderboardRequest
	4,  // 30: quiz.AuthService.Register:output_type -> quiz.AuthResponse
	4,  // 31: quiz.AuthService.Login:output_type -> quiz.AuthResponse
	9,  // 32: quiz.MatchmakingService.JoinMatchmaking:output_type -> quiz.JoinResponse
	11, // 33: quiz.MatchmakingService.LeaveMatchmaking:output_type -> quiz.LeaveResponse
	13, // 34: quiz.MatchmakingService.SubscribeToMatch:output_type -> quiz.MatchEvent
	18, // 35: quiz.QuizService.GetRoomQuestions:output_type -> quiz.QuestionsResponse
	20, // 36: quiz.QuizService.SubmitAnswer:output_type -> quiz.AnswerAck
	22, // 37: quiz.QuizService.StreamGameEvents:output_type -> quiz.GameEvent
	30, // 38: quiz.ScoringService.CalculateScore:output_type -> quiz.ScoreResponse
	32, // 39: quiz.ScoringService.GetLeaderboard:output_type -> quiz.LeaderboardResponse
	30, // [30:40] is the sub-list for method output_type
	20, // [20:30] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_quiz_proto_init() }
func file_proto_quiz_proto_init() {
	if File_proto_quiz_proto != nil {
		return
	}
	file_proto_quiz_proto_msgTypes[10].OneofWrappers = []any{
		(*MatchEvent_MatchFound)(nil),
		(*MatchEvent_MatchCancelled)(nil),
		(*MatchEvent_WaitingUpdate)(nil),
	}
	file_proto_quiz_proto_msgTypes[19].OneofWrappers = []any{
		(*GameEvent_Question)(nil),
		(*GameEvent_Leaderboard)(nil),
		(*GameEvent_RoundResult)(nil),
		(*GameEvent_MatchEnd)(nil),
		(*GameEvent_PlayerJoined)(nil),
		(*GameEvent_TimerSync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quiz_proto_rawDesc), len(file_proto_quiz_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_quiz_proto_goTypes,
		DependencyIndexes: file_proto_quiz_proto_depIdxs,
		EnumInfos:         file_proto_quiz_proto_enumTypes,
		MessageInfos:      file_proto_quiz_proto_msgTypes,
	}.Build()
	File_proto_quiz_proto = out.File
	file_proto_quiz_proto_goTypes = nil
	file_proto_quiz_proto_depIdxs = nil
}
